### ISSUE TITLE
Source map doesn't work properly in the console of Firefox.

### ISSUE THREAD

**Issue by begeeben** [seiyugi/goku.js#14]
Works in Chrome.

**Comment by dwi2** [comment]
Do you mean this?
![bug](https://cloud.githubusercontent.com/assets/644741/7539544/4743364c-f5da-11e4-9361-0236e218f67d.png)

**Comment by begeeben** [comment]
Yes. Good job!

**Comment by dwi2** [comment]
The line of console output is now correct in Firefox in latest master.
Though it says `goku.min.js`, but it actually means `/dist/goku.js` or `/goku.js`

![bug](https://cloud.githubusercontent.com/assets/644741/7555105/ba580d70-f773-11e4-8a7d-d7f6085e05b6.png)

I'll close this issue if you don't have any problem with it.
